name: Version Increment

on:
    workflow_dispatch:
        inputs:
            release_version:
                description: "Version to release (e.g., 1.0.0)"
                required: true
            release_code:
                description: "Version code for Android and iOS"
                required: true

permissions:
    contents: write
    pull-requests: write

jobs:
    version_increment:
        runs-on: ubuntu-latest

        steps:
            - name: Configure Git
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Update Flutter version in pubspec.yaml
              run: |
                  sed -i.bak "s/^version: .*/version: ${{ github.event.inputs.release_version }}+${{ github.event.inputs.release_code }}/" pubspec.yaml

            - name: Update version in Android build.gradle
              run: |
                  sed -i.bak "s/versionName \"[0-9.]\+\"/versionName \"${{ github.event.inputs.release_version }}\"/g" android/app/build.gradle
                  sed -i.bak "s/versionCode [0-9]\+/versionCode ${{ github.event.inputs.release_code }}/g" android/app/build.gradle

            - name: Update version in iOS project.pbxproj
              run: |
                  sed -i.bak "s/CURRENT_PROJECT_VERSION = [0-9]\+;/CURRENT_PROJECT_VERSION = ${{ github.event.inputs.release_code }};/" ios/Runner.xcodeproj/project.pbxproj
                  sed -i.bak "s/MARKETING_VERSION = [0-9.]\+;/MARKETING_VERSION = ${{ github.event.inputs.release_version }};/" ios/Runner.xcodeproj/project.pbxproj

            - name: Create release branch
              run: git checkout -b "release/v${{ github.event.inputs.release_version }}"

            - name: Commit changes
              run: |
                  git add pubspec.yaml android/app/build.gradle ios/Runner.xcodeproj/project.pbxproj
                  git commit -m "build: v${{ github.event.inputs.release_version }}+${{ github.event.inputs.release_code }}"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: "release/v${{ github.event.inputs.release_version }}"

            - name: Create Pull Requests
              run: |
                  curl -X POST \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/pulls \
                    -d @- <<EOF
                  {
                    "title": "[main] release v${{ github.event.inputs.release_version }}",
                    "head": "release/v${{ github.event.inputs.release_version }}",
                    "base": "main"
                  }
                  EOF

                  curl -X POST \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/pulls \
                    -d @- <<EOF
                  {
                    "title": "[develop] release v${{ github.event.inputs.release_version }}",
                    "head": "release/v${{ github.event.inputs.release_version }}",
                    "base": "develop"
                  }
                  EOF
