name: Version Increment

on:
    workflow_dispatch:
        inputs:
            release_version:
                description: "Version to release (e.g., 1.0.0)"
                required: true
            release_code:
                description: "Version code for Android and iOS"
                required: true

permissions:
    contents: write
    pull-requests: write

jobs:
    version_increment:
        runs-on: ubuntu-latest

        steps:
            - name: Configure Git
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            # ✅ Update Flutter version in pubspec.yaml
            - name: Update Flutter version in pubspec.yaml
              run: |
                  sed -i.bak "s/^version: .*/version: ${{ github.event.inputs.release_version }}+${{ github.event.inputs.release_code }}/" pubspec.yaml
                  rm -f pubspec.yaml.bak

            # ✅ Update versionCode and versionName in version.properties
            - name: Update Android version in version.properties
              run: |
                  echo "versionCode=${{ github.event.inputs.release_code }}" > android/version.properties
                  echo "versionName=${{ github.event.inputs.release_version }}" >> android/version.properties

            # ✅ Update version in iOS project.pbxproj
            - name: Update version in iOS project.pbxproj
              run: |
                  sed -i.bak "s/CURRENT_PROJECT_VERSION = [0-9]\+;/CURRENT_PROJECT_VERSION = ${{ github.event.inputs.release_code }};/" ios/Runner.xcodeproj/project.pbxproj
                  sed -i.bak "s/MARKETING_VERSION = [0-9.]\+;/MARKETING_VERSION = ${{ github.event.inputs.release_version }};/" ios/Runner.xcodeproj/project.pbxproj
                  rm -f ios/Runner.xcodeproj/project.pbxproj.bak

            # ✅ Debug modified files before commit
            - name: Debug pubspec.yaml
              run: cat pubspec.yaml

            - name: Debug version.properties
              run: cat android/version.properties

            - name: Debug iOS project.pbxproj
              run: cat ios/Runner.xcodeproj/project.pbxproj

            # ✅ Check for changes before committing
            - name: Check if there are changes
              id: check_changes
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "changes=true" >> $GITHUB_ENV
                  else
                    echo "changes=false" >> $GITHUB_ENV
                  fi

            # ✅ Commit changes if there are any
            - name: Commit changes if present
              if: env.changes == 'true'
              run: |
                  git add pubspec.yaml android/version.properties ios/Runner.xcodeproj/project.pbxproj
                  git commit -m "build: v${{ github.event.inputs.release_version }}+${{ github.event.inputs.release_code }}"

            # ✅ Push changes if commit happened
            - name: Push changes
              if: env.changes == 'true'
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: "release/v${{ github.event.inputs.release_version }}"

            # ✅ Create Pull Request if changes exist
            - name: Create Pull Requests
              if: env.changes == 'true'
              run: |
                  curl -X POST \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/pulls \
                    -d @- <<EOF
                  {
                    "title": "[main] release v${{ github.event.inputs.release_version }}",
                    "head": "release/v${{ github.event.inputs.release_version }}",
                    "base": "main"
                  }
                  EOF

                  # Create Pull Request to develop
                  curl -X POST \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/pulls \
                    -d @- <<EOF
                  {
                    "title": "[develop] release v${{ github.event.inputs.release_version }}",
                    "head": "release/v${{ github.event.inputs.release_version }}",
                    "base": "develop"
                  }
                  EOF
